version: "3.1"

services:
        nginx:
                build: .
                dockerfile: nginx.Dockerfile
                container_name: nginx
                ports:
                        - 80:80
                        - 443:443
                # links:
                #        - consul