version: '2'

services:
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=toor
        volumes:
            - /data/docker-data/mysql:/var/lib/mysql