version: '2'

services:
    grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
        volumes:
          - /data/docker-data/grafana:/var/lib/grafana
        environment:
          - GF_SERVER_ROOT_URL=http://grafana.tools.example.com
          - GF_SECURITY_ADMIN_PASSWORD=changeme
          - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
          - GF_SMTP_ENABLED=true
          - GF_SMTP_HOST=smtp.exmail.qq.com:465
          - GF_SMTP_USER=<username>
          - GF_SMTP_PASSWORD=<password>
          - GF_SMTP_FROM_ADDRESS=<email>
