version: '2'

services:
    dubbokeeper:
        container_name: dubbokeeper
        build:
            context: .
            dockerfile: dubbo/Dockerfile
        ports:
            - 8080:8080
            - 7070:7070
        # 由于 dubbo monitor 需要暴露 dubbo 服务，所以需要使用主机网络
        network_mode: host
#        environment:
#            - HOSTNAME=dubbokeeper
#
#        extra_hosts:
#            - dubbokeeper:host_ip
        depends_on:
            - mongodb