apiVersion: v1
kind: Service
metadata:
  name: date-server
  labels:
    app: date-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: date-server

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: date-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: date-server
    spec:
      containers:
      - name: date-server
        image: docker.io/rnburn/zipkin-date-server:latest
        ports:
        - containerPort: 8080
        env:
          - name: ZIPKIN_COLLECTOR_HOST
            value: zipkin

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: date-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: date-server
    servicePort: 8080
